; =====================
; === ИГРОК ===
; =====================

; Горизонтальная скорость перемещения игрока
horizontalSpeed = 3.0

; Начальный уровень негатива
initialNegative = 0
d
; Максимальный уровень негатива
maxNegative = 10

; Время полного заполнения шкалы
fillDuration = 1


; =====================
; === ПЛАТФОРМЫ ===
; =====================

; Сила прыжка от начальной платформы
initialPlatformJumpForce = 6.0

; Сила прыжка от появляющиеся платформы
platformJumpForce = 10.0

; Фиксированная высота следующей платформы над игроком
singlePlatformHeightOffset = 12.0

; Насколько платформа может выходить за экран (0.0 - 0.5)
platformHorizontalOverflow = 0.3


; =====================
; === НАЧАЛЬНАЯ ЗЕМЛЯ ===
; =====================

; Высота, при которой начальная земля пропадает (в метрах)
destroyHeightThreshold = 2.0


; =====================
; === КАМЕРА ===
; =====================

; Скорость следования камеры (0 - 1)
cameraSmoothSpeed = 0.25


; =====================
; === СЧЕТ ===
; =====================

; Символ единицы измерения
distanceUnit = m

; Сколько сантиметров в одной Unity-единице
centimetersPerUnit = 40


; =====================
; === PROGRESS BAR ===
; =====================

; Ускорение в начале сегмента
progressbarAcceleration = 2.0

; Замедление в конце сегмента
progressbarDeceleration = 3.0

; Максимальная скорость
progressbarMaxSpeed = 5.0

; Буст при переходе на новый сегмент
progressbarSegmentSwitchBoost = 1.2


; =====================
; === СПОСОБНОСТИ ===
; =====================

; Сила двойного прыжка
doubleJumpForce = 5.0

; Сила рывка вверх
upDashForce = 17.0

; Скорость горизонтального перемещения
sideDashSpeed = 7.0

; Время действия SideDash
sideDashTime = 0.5

; Сила крика
screamForce = 1.0


; =====================
; === СТОИМОСТИ СПОСОБНОСТЕЙ ===
; =====================

doubleJumpResourceCost = 5
upDashResourceCost = 8
sideDashResourceCost = 5
screamResourceCost = 1


; =====================
; === UI СПОСОБНОСТЕЙ ===
; =====================

; Цвет затемнения иконки (RGBA 0-1)
pressedColor = 0.6,0.6,0.6,1.0

; Время действия затемнения
pressDuration = 0.1
